version: '3'

networks:
  reverseproxy-main-network:
    external:
      name: reverseproxy-main-network

services:
  web:
    container_name: gitlab
    hostname: gitlab
    image: gitlab/gitlab-ce:latest
    ports:
      - 222:022
    volumes:
      - /opt/docker_gitlab/data:/var/opt/gitlab
      - /var/log/gitlab:/var/log/gitlab
      - /etc/gitlab:/etc/gitlab
    networks:
      - reverseproxy-main-network
    restart: always